### ISSUE TITLE
command 'test-explorer.reloading' not found

### ISSUE THREAD

**Issue by DownyBehind** [Florin-Popescu/vscode-unity-test-adapter#21]
When I click the 'Test Explorer: Reloading tests' button, vscode shows me this message.

      command 'test-explorer.reloading' not found

Please let me know how I can fix it. 

Thanks!

**Comment by Florin-Popescu** [comment]
Hello! This extension hasn't been maintained in a very long time. I suspect that there's been API changes in the original Test Explorer extension for which this was originally a plugin, or in vscode itself. 

I believe fixing #12 should address this. I'm starting work on that one but I cannot say yet how long that will take and I have very limited time.

**Comment by Florin-Popescu** [comment]
With the implementation of #12 the extension now lazy loads tests when opening a file in the test interface, when a file changes etc. For the moment it doesn't support forced loading. Do you require this or does the new behavior work good enough for you?

**Comment by Florin-Popescu** [comment]
Hello, it's been over a year with no news from you so I'm closing this. If you still need something, feel free to reopen it.
