### ISSUE TITLE
testCaseRegex was removed

### ISSUE THREAD

**Issue by NovaNekmit** [Florin-Popescu/vscode-unity-test-adapter#22]
4b02798ea165784d1404be577a18ced10924a034 removed `unityExplorer.testCaseRegex` from the package.json.

**Comment by BennyEvans** [comment]
It seems this has been fixed, but a release not yet created. @Florin-Popescu may you please create a new release when possible 😁 I've had to downgrade to keep my project working correctly.

**Comment by Florin-Popescu** [comment]
Hey! I've been having terrible issues with npm since end of august, see npm/cli/issues/4028. I can't package the extension so I am stuck for the moment.

**Comment by Florin-Popescu** [comment]
Turns out I was able to publish from a Raspberry Pi and not from my typical workstation. Try the update and let me know.

**Comment by jnz86** [comment]
Sounds like you are hot-discovering the use-case for developing in containers :)

**Comment by Florin-Popescu** [comment]
@jnz86 one day, when I'd have the time to set it up... Sure 😉

@NovaNekmit was this fixed properly? Can I close this?

**Comment by NovaNekmit** [comment]
The setting now works again, thank you.
