### ISSUE TITLE
Running in WSL?

### ISSUE THREAD

**Issue by felixeriksson** [Florin-Popescu/vscode-unity-test-adapter#23]
Hi, I installed this extension with the goal of running Unity-based (through esp-idf) unit tests for an ESP32 (the extension seems perfect for my needs). The tests can only be run on a Linux platform, and therefore I use WSL. However, when I run VSCode in WSL, I'm not seeing the test tab in the left hand menu. I do see it running directly in Windows, and the tests are discovered, but naturally I can't run the tests.

Do I need to configure something to make the test menu show up, or is there some other obstacle to running the extension in WSL?

**Comment by felixeriksson** [comment]
I'm running this configuration:
```
    "unityExplorer.debugConfiguration": "Unit Test",
    "unityExplorer.prettyTestCaseRegex": "test_(\\w+)",
    "unityExplorer.prettyTestFileRegex": "test_(\\w+)\\.c",
    "unityExplorer.testBuildApplication": "idf.py build",
    "unityExplorer.testBuildTargetRegex": ""
```

**Comment by Florin-Popescu** [comment]
Hello!

The extension uses lazy loading, so it doesn't scan your workspace at power on to not slow vscode down, but rather only when it would actually make sense to do it. One such trigger is when opening a .c file. 

In case you haven't already, could you try to open a random .c file from your workspace? Doesn't need to match any of your regexes. Just trying to rule out obvious stuff.

If not that, I would suspect some pathing issue in wsl. Could also be that the extension cannot match the file or test case regexes, but that should be unlikely given your configuration and the fact that it works on windows.

**Comment by felixeriksson** [comment]
Oh, that was it, the test menu showed up upon opening a .c file :) My knowledge about what goes on under the hood in VSCode is still limited. Thanks a lot for the help!
