### ISSUE TITLE
Configurable build tool

### ISSUE THREAD

**Issue by d-serj** [Florin-Popescu/vscode-unity-test-adapter#5]
Hi!
I am going to use your extension on Windows. I think it would be really good to make the build tool configurable by the user since default `make` cannot be run on Windows without MSYS2 or some other similar tool.
It could be `mingw32-make`, `ninja`, `cmake --build` and others instead.

https://github.com/Florin-Popescu/vscode-unity-test-adapter/blob/1e38d54c4d41c39a69d63ac9bf846db62e395bda/src/adapter.ts#L342

**Comment by Florin-Popescu** [comment]
Just published version 0.0.5 of the extension for which I added `unityExplorer.testBuildApplication` to configure the build tool.

Also note that I've changed the names for most of the settings to be clearer about their purpose so you will need to re-configure them.

Please let me know if it now works for you.
