### ISSUE TITLE
Customized build target

### ISSUE THREAD

**Issue by NovaNekmit** [Florin-Popescu/vscode-unity-test-adapter#8]
Currently, the executable path is used as build target, but some build systems may not work that way.

From the documentation, it is not obvious that `testExecutableFolder` is also the prefix for the build target, splitting it into two config settings, adding a flag to use `testSourceFolder` instead, or adding some regex functionality would be great.

Ie. for `tests/test_something.c` bazel may expect something like `bazel build tests:test_something` (but `bazel build tests/test_something` will also work) and output `bazel-bin/tests/test_something`.

I am currently solving this by setting `testBuildApplication` to bash and `testBuildArgs` to a small script that replaces the `bazel-bin/tests/` prefix with `tests:`, but that is far from optimal.

Please also add some more info to the `Cannot find test result path` error (ie if `unitUnderTestFolder` at L133 or `testSourceFolder` at L134 was the problem and what the actual path is).

**Comment by Florin-Popescu** [comment]
Thanks for the feedback! I like your regex idea and I'll still be looking at other ways in which I could use regexes to simplify the extension settings.

Split `testExecutableFolder` into `testBuildTargetRegex` and `testExecutableRegex`. Should be available in the marketplace in extension version 0.0.6. For your usecase, set `testBuildTargetRegex=tests:$1` and `testExecutableRegex=bazel-bin/tests/$1` and it should do it. Please let me know if this gives you any more issues.

I was also thinking that error handling in general could be improved but I don't have much time these days.  I am planning to migrate to the new [Testing API](https://code.visualstudio.com/api/extension-guides/testing) once it is finalized and that will change the way in which the extension does things, so I'll fix the error reporting together with that overhaul. Created #9 to keep this in mind.

**Comment by NovaNekmit** [comment]
Looks workable, thanks.

Unfortunately when I installed the new version, I also updated vscode and other addons, now no tests show up at all. So not really why sure what broke.

(Code 1.57.1, TestExplorerUI 2.20.4, Unity-Test-Adapter 0.0.6)

**Comment by Florin-Popescu** [comment]
> Looks workable, thanks.
> 
> Unfortunately when I installed the new version, I also updated vscode and other addons, now no tests show up at all. So not really why sure what broke.
> 
> (Code 1.57.1, TestExplorerUI 2.20.4, Unity-Test-Adapter 0.0.6)

Try to look at the settings `testSourceFolder` (relative to workspace root),  `testSourceFileRegex` and `testCaseRegex`. You need these 3 to be able to load up unit tests in the test view. If `testSourceFolder` and `testSourceFileRegex` match any file they should show up in the test UI even if the `testCaseRegex` doesn't match the test cases inside. That should help you pin down what's to blame.

You can give me some file & test name examples from your project and the settings you use and I may help you.

I am using the latest versions of vscode and TestExplorerUI and don't see any issues with them.

**Comment by NovaNekmit** [comment]
Looking into the change, I saw you also changed the `testSourceFileRegex` to match the full path (https://github.com/Florin-Popescu/vscode-unity-test-adapter/commit/a777a4198f72179107be97864fe63cc5eb5e3367#diff-90f5592a8a85ef6ea1f847351c4ec2ad2f646d34f426d1e9feb2ed7411f344ccR490), which broke my `^test_\w+\.c$` regex. Using `test_\w+\.c$` works. (I have some reports in that folder containing the filename, so I needed `$` matching. Thankfully `^` is not needed.)

**Comment by Florin-Popescu** [comment]
Oh, sorry about that. Meant to use `testSourceFileRegex` to match the full path and remove `testSourceFolder` altogether but then decided that `testSourceFolder` would be useful for very big projects to not check against every single file in the workspace. This change also affects `unitUnderTestFileRegex` so update that too if you used it.

Anyways it may be useful so regexes could match/exclude subfolders too, instead of just the filenames, so I think it should be kept this way.
